# This file was generated by GoReleaser. DO NOT EDIT.
cask "yummy" do
  name "yummy"
  desc "Terminal-based cookbook manager and recipe assistant"
  homepage "https://github.com/GarroshIcecream/yummy"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yummy"

  on_macos do
    on_intel do
      url "https://github.com/GarroshIcecream/yummy/releases/download/v#{version}/yummy_#{version}_darwin_amd64.tar.gz"
      sha256 "058dfe7c5df1b8a81d34424a96f9a9d2efe2b549fd89823e95211cb4f4e9ac34"
    end
    on_arm do
      url "https://github.com/GarroshIcecream/yummy/releases/download/v#{version}/yummy_#{version}_darwin_arm64.tar.gz"
      sha256 "c145f815010e5c9a2bae9144e2dbf53feb91cba5e7a20f8145b5448887d76371"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GarroshIcecream/yummy/releases/download/v#{version}/yummy_#{version}_linux_amd64.tar.gz"
      sha256 "3bdaedffff25795089a6a6e52693ee3d03de63b70661854b68270b32355dee6b"
    end
    on_arm do
      url "https://github.com/GarroshIcecream/yummy/releases/download/v#{version}/yummy_#{version}_linux_arm64.tar.gz"
      sha256 "b9efe5c12e6b494aa1a89d1e86d13a59cf8db793eb82067fbdcfaaf1bf6fc0e5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yummy"]
    end
  end

  caveats do
    "Yummy is a terminal-based application. Run 'yummy --help' to get started."
  end

  # No zap stanza required
end
